import operator
from typing import Annotated
from typing_extensions import TypedDict
from bedrock import MODELS

# ── State ─────────────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    # Full conversation history.
    # operator.add means each update APPENDS to the list — never overwrites.
    messages: Annotated[list[dict], operator.add]

    # Which Bedrock model to use for the main LLM node.
    # No annotation = last-write-wins (the classifier sets this each turn).
    model_id: str

    # Bedrock toolSpec list fetched from MCP at startup.
    # Passed to every llm_node call so Bedrock knows what tools are available.
    # Last-write-wins — set once before the graph runs, never changes mid-turn.
    tools: list[dict]

    # Short execution ID (8 hex chars) generated by classify_node at the start
    # of every turn. Passed through state so llm_node and tool_node can attach
    # the same ID to their CloudWatch log entries, tying a full turn together.
    execution_id: str
